## Plotting of the interaction network generated by the Python script
## get_graph.py
# The interaction network is normalized by the number of teacher of each school.

library("igraph")
library("ggplot2")

radian.rescale <- function(x, start=0, direction=1) {
  c.rotate <- function(x) (x + start) %% (2 * pi) * direction
  c.rotate(scales::rescale(x, c(0, 2 * pi), range(x)))
}


args <- commandArgs(trailingOnly = TRUE)

## Input file with the interactions of the network of one school
social_net_edges <- read.csv(args[1], sep=";")
## Input file with the vertices of the network of one school (a.k.a. school roles)
social_net_nodes <- read.csv(args[2], sep=";")
## Name of the output PDF file
out_pdf <- args[3]
## The number of teachers in the school
num_teachers <- strtoi(args[4])

## Constructing the interaction network for plotting
g <- graph_from_data_frame(d=social_net_edges, vertices=social_net_nodes, directed=TRUE)

gg <- g

## School roles
nodes_names <- c("tutor", "teaching\nassistant", "academic\ncoordinator",
                "special education\nteacher", "students", 
                "teaching\nassistant", "students\nfamily", "teacher\nfamily", 
                "school\ninspector", "department\nhead", 
                "pedagogical-technical\ncoordinator", "management team\nmember",
                "student support\nprofessional", "external\nprofessional", 
                "classroom\nteacher", "external\nclassroom\nteacher", 
                "specialist subject\nteacher", "trainee\nteacher",
                "legal\nguardian", "classroom\nassistant")

## Defining the color for each vertex /school role
n  <- length(nodes_names)
col = rainbow(n)

color_nodes <- vector("numeric", n)
color_labels <- c()

names(color_nodes) <- nodes_names
names(color_labels) <- color_labels
i=1
for(nn in nodes_names) {
    color_nodes[nn] = col[i]
    color_labels[nn] = "#000000FF"
    i=i+1
}

## Edges colors
colrs <- c(Info = "coral2",
           Ayuda = "forestgreen",
           Colab = "lightseagreen")

## Interaction names
interac_names <- c(Info = "Information",
                   Ayuda = "Support",
                   Colab = "Collaboration")

## Type of interactions
interactions <- c("Info", "Ayuda", "Colab")

## Normalization of the edge weight by the number of teachers
E(gg)$width <- (E(gg)$weight/num_teachers)*100
E(gg)$width <- log(E(gg)$width) + 1

pdf(file = out_pdf, width=10)
par(mar=c(2,2,2,2), mfrow = c(1,1))

## Computing the position of the vertices labels
num_vertex = length(V(gg))
lab.locs <- radian.rescale(x=1:num_vertex, direction=-1, start=0)

## Plot one interaction network per type of interaction
for(inter in interactions) {
  edges_filter = E(gg)[type==inter]
  g2 <- subgraph.edges(gg, edges_filter, delete.vertices = FALSE)

  vertex.col <- color_nodes[V(g2)$name]
  vertex.lab.col <- color_labels[V(g2)$name]

  deg = degree(g2)

  for(k in names(deg)) {
      if(deg[k] == 0) {
          vertex.col[k] = "#AAAAAA00"
          vertex.lab.col[k] = "#AAAAAA00"
      }
  }
  
  edge.col <- colrs[E(g2)$type]
  par(lheight = 0.6) 
  plot(g2,
       main = interac_names[inter],
       edge.arrow.size=.8,
       edge.curved=0,
       edge.color = edge.col,
       vertex.color=vertex.col,
       vertex.frame.color=vertex.col,
       vertex.label=V(g2)$name,
       vertex.label.color=vertex.lab.col,
       vertex.label.cex=1,
       vertex.label.font=2,
       vertex.label.degree=lab.locs,
       vertex.label.dist=3,
       vertex.size = 10,
       layout=layout_in_circle,
       margin=0.09)

}


## Plot an interaction network with the tree types of interactions
vertex.col <- color_nodes[V(gg)$name]
vertex.lab.col <- color_labels[V(gg)$name]

deg = degree(gg)

for(k in names(deg)) {
    if(deg[k] == 0) {
          vertex.col[k] = "#AAAAAA00"
          vertex.lab.col[k] = "#AAAAAA00"
    }
}

edge.col <- colrs[E(gg)$type]

par(lheight = 0.6) ## Interlineado

plot(gg,
     main = "All interactions",
     edge.arrow.size=.8,
     edge.color = edge.col,
     vertex.color=vertex.col,
     vertex.frame.color=vertex.col,
     vertex.label=V(gg)$name,
     vertex.label.color=vertex.lab.col,
     vertex.label.cex=1,
     vertex.label.font=2,
     vertex.label.degree=lab.locs,
     vertex.label.dist=3,
     vertex.size = 10,
     layout=layout_in_circle,
     margin=0.09)


leg.col <- colrs[interactions]

legend("bottomright", legend=interac_names, lty=1,
       col=leg.col, cex=1, bty="n", ncol=1, lwd=2.5)
